swagger: "2.0"
info:
  description: "Сервис работы с аккаунтами пользователей (регистрация, сброс пароля, подтверждение аккаунта и т.д."
  version: "1.0.0"
  title: "Account Management Service "
  contact:
    url: "https://github.com/TonyHikas"
    name: "GitHub Account"

schemes:
- "https"
paths:
  /account/register:
    post:
      tags:
      - "Account"
      summary: "Регистрация"
      description: ""
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            email:
              type: "string"
            password:
              type: "string"

      responses:
        201:
          description: Created
          schema:
            type: "object"
            properties:
              token:
                type: "string"
        400:
          description: "Ошибка во входных данных"
          schema:
            type: "object"
            properties:
              email:
                type: "array"
                items:
                  type: "string"
                  enum:
                  - "Enter a valid email address."
              password:
                type: "array"
                items:
                  type: "string"
                  enum:
                  - "Пароль должен состоять из 8 латинских символов, содержать как мининум 1 заглавную букву и 1 цифру"
  /account/auth:
    post:
      tags:
      - "Account"
      summary: "Логин"
      description: ""
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            email:
              type: "string"
            password:
              type: "string"
      responses:
        200:
          description: OK
          schema:
            type: "object"
            properties:
              token:
                type: "string"
        400:
          description: "Ошибка во входных данных"
          schema:
            type: "object"
            properties:
              email:
                type: "array"
                items:
                  type: "string"
                  enum:
                  - "Enter a valid email address."
              error:
                type: "array"
                items:
                  type: "string"
                  enum:
                  - "Неправильный email или пароль"

  /account/reset_password_key:
    post:
      tags:
      - "Account"
      summary: "Запрос ключа для сброса пароля"
      description: ""
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            email:
              type: "string"
      responses:
        200:
          description: OK
        400:
          description: "Ошибка во входных данных"
          schema:
            $ref: '#/definitions/EmailError'
        429:
          description: "Запрос можно отправлять не чаще 1 раза в минуту"

  /account/reset_password:
    post:
      tags:
      - "Account"
      summary: "Сброс пароля"
      description: ""
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            email:
              type: "string"
            key:
              type: "string"
            new_password:
              type: "string"
      responses:
        200:
          description: OK
        400:
          description: "Ошибка во входных данных"
          schema:
            type: "object"
            properties:
              email:
                type: "array"
                items:
                  type: "string"
                  enum:
                  - "Enter a valid email address."
              key:
                type: "array"
                items:
                  type: "string"
                  enum:
                  - "Неправильный ключ"
              new_password:
                type: "array"
                items:
                  type: "string"
                  enum:
                  - "Введите пароль, который не использовали ранее"

  /account/reset_email_key:
    post:
      tags:
      - "Account"
      summary: "Запрос ключа для смены email"
      description: ""
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            email:
              type: "string"
      responses:
        200:
          description: OK
        400:
          description: "Ошибка во входных данных"
          schema:
            $ref: '#/definitions/EmailError'
        429:
          description: "Запрос можно отправлять не чаще 1 раза в минуту"

  /account/reset_email:
    post:
      tags:
      - "Account"
      summary: "Смена email"
      description: ""
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            email:
              type: "string"
            key:
              type: "string"
            new_email:
              type: "string"
      responses:
        200:
          description: OK
        400:
          description: "Ошибка во входных данных"
          schema:
            type: "object"
            properties:
              email:
                type: "array"
                items:
                  type: "string"
                  enum:
                  - "Enter a valid email address."
              key:
                type: "array"
                items:
                  type: "string"
                  enum:
                  - "Неправильный ключ"
              new_password:
                type: "array"
                items:
                  type: "string"
                  enum:
                  - "Пользователь с таким email уже существует"

  /account/confirm_key:
    post:
      tags:
      - "Account"
      summary: "Запрос ключа для подтверждения аккаунта"
      description: ""
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            email:
              type: "string"
      responses:
        200:
          description: OK
        400:
          description: "Ошибка во входных данных"
          schema:
            $ref: '#/definitions/EmailError'
        429:
          description: "Запрос можно отправлять не чаще 1 раза в минуту"

  /account/confirm:
    post:
      tags:
      - "Account"
      summary: "Подтверждение аккаунта"
      description: ""
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            email:
              type: "string"
            key:
              type: "string"
      responses:
        200:
          description: OK
        400:
          description: "Ошибка во входных данных"
          schema:
            type: "object"
            properties:
              email:
                type: "array"
                items:
                  type: "string"
                  enum:
                  - "Enter a valid email address."
              key:
                type: "array"
                items:
                  type: "string"
                  enum:
                  - "Срок действия ключа истек"

  /account/info:
    post:
      tags:
      - "Account"
      summary: "Информация о пользователе"
      description: ""
      responses:
        200:
          description: OK
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
              confirmed:
                type: "boolean"
              is_superuser:
                type: "boolean"
              date_joined:
                type: "string"
              email:
                type: "string"
        401:
          description: "Authentication credentials were not provided."

  /account/admin_stat:
    get:
      tags:
      - "Account"
      summary: "Статистика о кол-ве регистраций"
      description: ""
      responses:
        200:
          description: OK
          schema:
            type: "object"
            properties:
              count:
                type: "integer"
              today:
                type: "integer"
        401:
          description: "Authentication credentials were not provided."
        403:
          description: "Доступ только администраторам"

definitions:
  EmailError:
    type: "object"
    properties:
      email:
        type: "array"
        items:
          type: "string"
          enum:
          - "Enter a valid email address."


